device = "wlan1mon"
mode = "Host"

[agent]
platform = "Linux"
command = ["ssh", "rpi", "bash"]
after_connected = """
conn.send("exec sudo -s\\n");
conn.send("whoami\\n");
let id = conn.read_line();
debug("login as: " + id);
if id != "root\\n" {
    throw "not root";
}
"""
